### ISSUE TITLE
AttributeError: 'ResidualCouplingTransformersLayer2' object has no attribute 'remove_weight_norm'

### ISSUE THREAD

**Issue by Serdcoff** [FENRlR/MB-iSTFT-VITS2#18]
Hi there, I have this error when I want to convert model weight to onnx model.
How can I solve the problem?

Using mel posterior encoder for VITS2
Multi-band iSTFT VITS2
INFO:root:dec.stft.forward_basis is not in the checkpoint
INFO:root:dec.stft.inverse_basis is not in the checkpoint
INFO:root:Loaded checkpoint 'logs/models/G_48000.pth' (iteration 242)
Removing weight norm...
Traceback (most recent call last):
  File "onnx_export.py", line 79, in <module>
    net_g.flow.remove_weight_norm() # Remove weightnorm in flows - a8d9f74
  File "/MB-iSTFT-VITS2/models.py", line 759, in remove_weight_norm
    l.remove_weight_norm()
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ResidualCouplingTransformersLayer2' object has no attribute 'remove_weight_norm'

**Comment by Serdcoff** [comment]
From my experience, I will add what I personally encountered.
In requirements.txt you have row with pyopenjtalk==0.2.0. There was a problem for me on env witho building the wheel. I added pyopenjtalk==0.2.0 --no-build-isolation and everything was good.
Also zoneinfo is requid, but the supported version of python is >=3.9, but your app need 3.8.  I had to change several files to "from backports.zoneinfo import zoneinfo" from "import zoneinfo"

Now I'm trying to run inference.ipynb to check the model but there was a problem with error 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[11], line 1
----> 1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 import matplotlib.pyplot as plt
      3 import IPython.display as ipd

File ~/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2456, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2454     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2455 with self.builtin_trap:
-> 2456     result = fn(*args, **kwargs)
   2458 # The code below prevents the output from being displayed
   2459 # when using magics with decorator @output_can_be_silenced
   2460 # when the last Python token in the expression is a ';'.
   2461 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~/.local/lib/python3.9/site-packages/IPython/core/magics/pylab.py:99, in PylabMagics.matplotlib(self, line)
     97     print("Available matplotlib backends: %s" % backends_list)
     98 else:
---> 99     gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100     self._show_matplotlib_backend(args.gui, backend)

File ~/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3630, in InteractiveShell.enable_matplotlib(self, gui)
   3609 def enable_matplotlib(self, gui=None):
   3610     """Enable interactive matplotlib and inline figure support.
   3611 
   3612     This takes the following steps:
   (...)
   3628         display figures inline.
   3629     """
-> 3630     from matplotlib_inline.backend_inline import configure_inline_support
   3632     from IPython.core import pylabtools as pt
   3633     gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)

File ~/.local/lib/python3.9/site-packages/matplotlib_inline/__init__.py:1
----> 1 from . import backend_inline, config  # noqa
      2 __version__ = "0.1.6"  # noqa

File ~/.local/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:6
      1 """A matplotlib backend for publishing figures via display_data"""
      3 # Copyright (c) IPython Development Team.
      4 # Distributed under the terms of the BSD 3-Clause License.
----> 6 import matplotlib
      7 from matplotlib import colors
      8 from matplotlib.backends import backend_agg

File ~/.local/lib/python3.9/site-packages/matplotlib/__init__.py:174
    169         if LooseVersion(module.__version__) < minver:
    170             raise ImportError("Matplotlib requires {}>={}; you have {}"
    171                               .format(modname, minver, module.__version__))
--> 174 _check_versions()
    177 # The decorator ensures this always returns the same handler (and it is only
    178 # attached once).
    179 @functools.lru_cache()
    180 def _ensure_handler():

File ~/.local/lib/python3.9/site-packages/matplotlib/__init__.py:159, in _check_versions()
    155 def _check_versions():
    156 
    157     # Quickfix to ensure Microsoft Visual C++ redistributable
    158     # DLLs are loaded before importing kiwisolver
--> 159     from . import ft2font
    161     for modname, minver in [
    162             ("cycler", "0.10"),
    163             ("dateutil", "2.1"),
   (...)
    166             ("pyparsing", "2.0.1"),
    167     ]:
    168         module = importlib.import_module(modname)

ImportError: numpy.core.multiarray failed to import
