### ISSUE TITLE
ONNX format

### ISSUE THREAD

**Issue by AigizK** [FENRlR/MB-iSTFT-VITS2#3]
You could use  this PR: https://github.com/p0p4k/vits2_pytorch/pull/43

**Comment by w11wo** [comment]
I've attempted to apply the same exporting script to MB-iSTFT-VITS2, but I'm running into some trouble during the export. I think it's related to complex numbers being only partially supported by `torch.onnx`, or something along those lines. 

Here's the error log in case anyone's interested:
```
Traceback (most recent call last):
  File "/content/MB-iSTFT-VITS2/export_onnx.py", line 110, in <module>
    main()
  File "/content/MB-iSTFT-VITS2/export_onnx.py", line 91, in main
    torch.onnx.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 658, in _optimize_graph
    _C._jit_pass_erase_number_types(graph)
RuntimeError: Unknown number type: complex
```

To reproduce, I've prepared a Colab notebook [here](https://colab.research.google.com/drive/1XVYrUTgQwkP5y-bozop5cvuibx6GyirE?usp=sharing). It uses the models from [here](https://github.com/FENRlR/MB-iSTFT-VITS2/issues/2).

**Comment by FENRlR** [comment]
https://github.com/pytorch/pytorch/issues/81075
It looks like we need more time for this.

**Comment by nshmyrev** [comment]
It is actually easy to export, see the patch here:

https://github.com/alphacep/MB-iSTFT-VITS2/commit/29c91d478bc16e653cd5de7c9163e2ba45ed7c6c
